### ISSUE TITLE
Variables declared in onGetProperty persist across calls

### ISSUE THREAD

**Issue by JeremyGrieshop** [afw-org/afw#11]
Suppose I have the following implementation of a model `onGetProperty`:

```
#! afw

loc l = [];
add_entries(l, "x");

return l;
```

If I get a property through a model, using this `onGetProperty`, I will get a list containing the string `"x"`, as I expected (`[ "x" ]`).

However, if I perform another get_object request, the list will look like: `[ "x", "x" ]`. It appears to re-use the same list in memory from the previous call.

**Comment by mike000000000** [comment]
```loc x = ['x1','x2',{'a':1}];
loc y = x;
loc z = x[2];
println('z=', z);
y[1] = 'y1';
y[2]['a'] = 2;
println('x=', x);
println('y=', y);
println('z=', z);
```

```z={"a":1}
x=["x1","y1",{"a":2}]
y=["x1","y1",{"a":2}]
z={"a":2}```


ran this in chrome developer tool and got similar results:
```
let y = x
let z = x[2]
console.log('z=', z)
y[1] = 'y1'``

I'm not 100% convinced that the #11 bug is completely fixed in all conditions. Since we have a few built in functions that modify parameters plus script functions might try to modify literals passed, I'm going to make sure literals are marked as immutable. The effect is that instead of the #11 bug getting an incorrect result, an error will be thrown is something sneaks past. An example where this error would be thrown is if the add_entries() function is called with first parameter being a literal.

**Comment by mike000000000** [comment]
The original issue is fixed, but it uncovered that a review of literals passed as function parameters that might be returned in some form is also needed.  In addition, the get_object() and review_objects() should return objects that are mutable, especially their meta. This issue is repurposed to cover these items as well.

**Comment by mike000000000** [comment]
List literals are now marked as immutable and cloned on assignment. This fixes this issue so I believe it can be closed. @JeremyGrieshop 

Issue #17 has been created to make object literals immutable which can cause a similar bug.
