### ISSUE TITLE
Implement for-of

### ISSUE THREAD

**Issue by JeremyGrieshop** [afw-org/afw#21]
The following code produces a parser error that `i already defined`:

```
for (loc i = 0; i < 10; i+=1) {
}

loc i;
for (i = 0; i < 10; i+=1) {
}

return 0;
```

I believe `i` would be within the scope of that `for` loop.  However, if I remove the line `loc i;`, then it tells me `Variable i is not defined`.

**Comment by mike000000000** [comment]
Note, the same problem that was in the for statement was also in try statement. Both are fixed.

**Comment by JeremyGrieshop** [comment]
I *think* it still happens in `foreach`:

```
#!/usr/bin/env afw

loc arr = [ 'a', 'b', 'c' ];

foreach loc x of arr {
  println(x);
}

foreach loc x of arr {
  println(x);
}
```

**Comment by mike000000000** [comment]
While fixing scope for foreach I needed to change enough things that I went ahead and added the for-of statement syntax. Options are to remove for-of, remove foreach, or keep both.

**Comment by mike000000000** [comment]
@JeremyGrieshop will you please convert foreach in tests to for-of?

**Comment by JeremyGrieshop** [comment]
@mike000000000 I think `foreach` can be removed. We'll keep this open to examine some of the 262 conformance tests results for `for-of`.
