### ISSUE TITLE
Were appropriate, change messages to read better by enclosing a literal in quotes

### ISSUE THREAD

**Issue by mike000000000** [afw-org/afw#42]
In the context of error messages, here's an example of a message that could be slightly changed to read better by simply enclosing a literal in quotes:

`Unknown built-in function this` -> `Unknown built-in function 'this'`

_Originally posted by @JeremyGrieshop in https://github.com/afw-org/afw/issues/28#issuecomment-1649887614_

**Comment by mike000000000** [comment]
We use macros like AFW_UTF8_FMT in our messages. I followed an APR convention where you have to put a %" before these. I'll change it where we don't have that %". So instead of:

```
        AFW_LOG_FZ(debug, xctx,
            "Adaptor %" AFW_UTF8_FMT
            " specified modelLocationAdaptorId %" AFW_UTF8_FMT
            ".",
            AFW_UTF8_FMT_ARG(&adaptor->adaptor_id),
            AFW_UTF8_FMT_ARG(self->model_location_adaptor_id));
```

it would be:

```
        AFW_LOG_FZ(debug, xctx,
            "Adaptor " AFW_UTF8_FMT
            " specified modelLocationAdaptorId " AFW_UTF8_FMT
            ".",
            AFW_UTF8_FMT_ARG(&adaptor->adaptor_id),
            AFW_UTF8_FMT_ARG(self->model_location_adaptor_id));
```

This will allow us to have additional AFW_UTF8_FMT macros like AFW_UTF8_FMT_Q to quote (whatever quote is) the substitution.

Getting rid of the % is pretty straight forward. Then we can review the AFW_UTF8_FMTs to find the ones that should have `_Q` added. We can fix a lot of other quoting errors during this pass as well.

This will introduce no more runtime overhead.

**Comment by mike000000000** [comment]
@JeremyGrieshop a90c466 is my shot at fixing the quotes in compiler error messages. They should be easy to scan.

We probably should review all of the AFW_THROW* messages at some point, but what's already done may be good enough to close this issue.

**Comment by mike000000000** [comment]
@JeremyGrieshop 7b5e9a1 have fixed most of the things that need quoting in AFW_THROW along with a few other places.

**Comment by JeremyGrieshop** [comment]
I've reviewed these and they all look like good messages for using the quoted literals.
