### ISSUE TITLE
Remove all support for expression tuples

### ISSUE THREAD

**Issue by mike000000000** [afw-org/afw#56]
Expression tuples seemed like a good idea years ago, but with adaptive script support, their need is diminished
and they are hard to maintain. We've decided to remove them.

**Comment by mike000000000** [comment]
`_AdaptiveAnnotation_`, the annotated value type, and the annotate() function are also being removed.

**Comment by mike000000000** [comment]
The expression_definition value type can also go since it was only used by expression tuple

**Comment by mike000000000** [comment]
@JeremyGrieshop I think I'm finished with all I'm planning to do on this one but let me know if you see something else I missed.

**Comment by JeremyGrieshop** [comment]
Also removed from UI and docs.
